name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cranberyxl'

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn
        run: corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Configure Yarn for publishing
        run: |
          yarn config set npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmAuthToken "${{ secrets.GITHUB_TOKEN }}"
          yarn config set npmScopes.cranberyxl.npmRegistryServer "https://npm.pkg.github.com"

      - name: Publish to GitHub Package Registry
        run: yarn npm publish
